# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"

  # Backend
  - package-ecosystem: "gomod"
    directory: /backend/lambdas/flavor
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: /backend/lambdas/flavors
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: /backend/lambdas/restaurant
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: /backend/lambdas/restaurants
    schedule:
      interval: "weekly"

  # Terraform
  - package-ecosystem: "terraform"
    directory: /terraform
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
