name = "api"
compatibility_date = "2023-12-01"

[vars]
RESTAURANTS_API_BASE_URL = "https://www.culvers.com/api"
RESTAURANT_SCRAPE_BASE_URL = "https://www.culvers.com/restaurants"
BASE_IMAGE_URL = "https://cdn.culvers.com/menu-item-detail"
LOGO_SVG_URL = "https://cdn.culvers.com/layout/logo.svg"
