/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FlavorsImport } from './routes/flavors'
import { Route as IndexImport } from './routes/index'
import { Route as RestaurantsSlugImport } from './routes/restaurants.$slug'
import { Route as FlavorsSlugImport } from './routes/flavors_.$slug'

// Create/Update Routes

const FlavorsRoute = FlavorsImport.update({
  path: '/flavors',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantsSlugRoute = RestaurantsSlugImport.update({
  path: '/restaurants/$slug',
  getParentRoute: () => rootRoute,
} as any)

const FlavorsSlugRoute = FlavorsSlugImport.update({
  path: '/flavors/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flavors': {
      preLoaderRoute: typeof FlavorsImport
      parentRoute: typeof rootRoute
    }
    '/flavors/$slug': {
      preLoaderRoute: typeof FlavorsSlugImport
      parentRoute: typeof rootRoute
    }
    '/restaurants/$slug': {
      preLoaderRoute: typeof RestaurantsSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FlavorsRoute,
  FlavorsSlugRoute,
  RestaurantsSlugRoute,
])

/* prettier-ignore-end */
